#!/bin/bash
#Data:2018-08-22
#Version:5.0
#Author:shunny(1071607787@qq.com)

a=e06af0637d07fe1e88efa05baec07286.jpg
b=/usr/share/backgrounds/tedu-wallpaper-01.png

if [ -z $1 ];then
	echo "cw [壁纸路径]"
	exit 3
elif [ ! -e $1 ];then
	echo "更换的壁纸不存在"
	wget ftp://172.40.62.101/wallpaper/tedu-wallpaper-2018.png
	for x in $a $b
        do
                        rm -f $x &>/dev/null
                        cp tedu-wallpaper-2018.png $x &>/dev/null
        done
        echo 更换完毕
else
	for x in $a $b
	do
			rm -f $x &>/dev/null
			cp $1 $x &>/dev/null
	done
	echo 更换完毕
fi



       


